table DimCustomers
	lineageTag: f6a72ab9-60a6-41b2-aad1-ff25c8fa208f

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 1a983581-bcac-447b-a691-e87388527307
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: f5fb65d8-5508-42b4-8b23-a1f2f069f800
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 880c9b53-0c75-40fa-a28b-7f2c88c4042b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition DimCustomers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Masaüstü 2025\Power BI Proje\first_project\supermarket.xlsx"), null, true),
				    #"Tableau Superstore_Sheet" = Source{[Item="Tableau Superstore",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Tableau Superstore_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"City", type text}, {"Country", type text}, {"Customer Name", type text}, {"Manufacturer", type text}, {"Order Date", type date}, {"Order ID", type text}, {"Postal Code", Int64.Type}, {"Product Name", type text}, {"Region", type text}, {"Segment", type text}, {"Ship Date", type date}, {"Ship Mode", type text}, {"State", type text}, {"Sub-Category", type text}, {"Discount", type number}, {"Number of Records", Int64.Type}, {"Profit", type text}, {"Profit Ratio", type number}, {"Quantity", Int64.Type}, {"Sales", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Profit", "Profit - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","$","",Replacer.ReplaceText,{"Profit - Copy"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Profit - Copy", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Profit - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Columns","$","",Replacer.ReplaceText,{"Profit"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"Profit", Currency.Type}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type2","$","",Replacer.ReplaceText,{"Sales"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value2",{{"Sales", Currency.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type3",{"City", "Country", "Customer Name", "Region", "Segment", "State"}),
				    #"Sorted Rows1" = Table.Sort(#"Removed Other Columns",{{"Customer Name", Order.Ascending}, {"Segment", Order.Ascending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows1"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Duplicates",{"City", "Country", "Region", "State"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns1",{{"Customer Name", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Customer Name", "Segment"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Customer ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

