table DimLocation
	lineageTag: 6a3c599a-18d4-479d-96e1-7bd697db9c40

	column 'Location ID'
		dataType: int64
		formatString: 0
		lineageTag: bc14b22f-92aa-4757-8795-9f74aeb92347
		summarizeBy: none
		sourceColumn: Location ID

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6732aab3-fbd4-4215-a8c2-cc44b81a63d5
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e209561e-415d-4263-82f7-eef577328f9c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 9deb21a4-7860-470f-ab1f-8437c20c8c52
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2bbdba7d-49e6-4bdd-996a-32c94760c3b0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b067efd9-374e-4d07-9f08-1e7594f37f26
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition DimLocation = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Masaüstü 2025\Power BI Proje\first_project\supermarket.xlsx"), null, true),
				    #"Tableau Superstore_Sheet" = Source{[Item="Tableau Superstore",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Tableau Superstore_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"City", type text}, {"Country", type text}, {"Customer Name", type text}, {"Manufacturer", type text}, {"Order Date", type date}, {"Order ID", type text}, {"Postal Code", Int64.Type}, {"Product Name", type text}, {"Region", type text}, {"Segment", type text}, {"Ship Date", type date}, {"Ship Mode", type text}, {"State", type text}, {"Sub-Category", type text}, {"Discount", type number}, {"Number of Records", Int64.Type}, {"Profit", type text}, {"Profit Ratio", type number}, {"Quantity", Int64.Type}, {"Sales", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Profit", "Profit - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","$","",Replacer.ReplaceText,{"Profit - Copy"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Profit - Copy", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Profit - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Columns","$","",Replacer.ReplaceText,{"Profit"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"Profit", Currency.Type}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type2","$","",Replacer.ReplaceText,{"Sales"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value2",{{"Sales", Currency.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type3",{"City", "Country", "Postal Code", "Region", "State"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Other Columns",{{"City", Order.Ascending}, {"Postal Code", Order.Ascending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"City", "Country", "State"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "City", "Country", "Postal Code", "Region", "State"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Location ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

