table DimOrders
	lineageTag: 2497b177-dc79-411e-b295-9233f880cd22

	column 'Order ID'
		dataType: string
		lineageTag: 2b79bc48-eef4-42fa-8a32-a8fa19df2f93
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 53edc557-fa99-47be-8c65-b8dca801691c
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 435448fa-546d-4e6e-8c33-ab938ced4adf
			defaultHierarchy: LocalDateTable_f43b75da-cff3-4d79-a499-f3203d2c340b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a4f8a372-a60c-483d-b93c-83e111a1b050
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 40e9c9a8-4e43-439a-9a26-37175d02102a
			defaultHierarchy: LocalDateTable_06733b14-b423-4b85-8101-5b5791f854b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 8a63e628-f980-4f3d-b3f3-9c10f54a428c
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	partition DimOrders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Masaüstü 2025\Power BI Proje\first_project\supermarket.xlsx"), null, true),
				    #"Tableau Superstore_Sheet" = Source{[Item="Tableau Superstore",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Tableau Superstore_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"City", type text}, {"Country", type text}, {"Customer Name", type text}, {"Manufacturer", type text}, {"Order Date", type date}, {"Order ID", type text}, {"Postal Code", Int64.Type}, {"Product Name", type text}, {"Region", type text}, {"Segment", type text}, {"Ship Date", type date}, {"Ship Mode", type text}, {"State", type text}, {"Sub-Category", type text}, {"Discount", type number}, {"Number of Records", Int64.Type}, {"Profit", type text}, {"Profit Ratio", type number}, {"Quantity", Int64.Type}, {"Sales", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Profit", "Profit - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","$","",Replacer.ReplaceText,{"Profit - Copy"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Profit - Copy", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Profit - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Removed Columns","$","",Replacer.ReplaceText,{"Profit"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"Profit", Currency.Type}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type2","$","",Replacer.ReplaceText,{"Sales"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value2",{{"Sales", Currency.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type3",{"Order Date", "Order ID", "Ship Date", "Ship Mode"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Order ID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Order ID", "Order Date", "Ship Date", "Ship Mode"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

